# Generated by Django 4.0 on 2022-01-02 19:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_start', models.DateField()),
                ('data_stop', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
