# Generated by Django 4.0 on 2022-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_achieve_data_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieve',
            name='data_stop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
