# Generated by Django 4.0 on 2022-01-02 21:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_achieve_data_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieve',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achieve',
            name='data_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
