# Generated by Django 4.0 on 2022-01-02 21:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_achieve_content_alter_achieve_data_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieve',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
