# Generated by Django 4.0 on 2022-01-02 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_achieve_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieve',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='achieve',
            name='data_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
