# Generated by Django 4.0 on 2022-01-03 16:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_achieve_certificate_alter_achieve_data_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achieve',
            old_name='content',
            new_name='list_studied',
        ),
        migrations.AddField(
            model_name='achieve',
            name='benefit',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achieve',
            name='links',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
