# Generated by Django 3.2.11 on 2022-01-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_rename_content_achieve_list_studied_achieve_benefit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieve',
            name='visible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achieve',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='img/achievements/'),
        ),
    ]
